apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-p2zb
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0050-tenant/tkrw-pr712-0075-0050-app/devfile-sample-p2zb@sha256:6c66a98212e50f67aa8065c216a50e3de2e1585ff07844514f2977d5f7193130
        name: my-nodejs
        resources: {}
status: {}
